import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuth } from '@/src/auth';
import { LocationPicker, useFarmLocation } from '@/src/location';
import Assistant from '@/src/screens/Assistant';
import Diary from '@/src/screens/Diary';
import { CropSheet, DiagnosisSheet, LandSheet } from '@/src/screens/FarmSheets';
import Home from '@/src/screens/Home';
import Market from '@/src/screens/Market';
import { colors } from '@/src/theme';
import { showToast, ToastHost } from '@/src/toast';
import { Badge, Button, Enter, ErrorNote, Icon, IconName, Lang, messageOf, s, Sheet, tr } from '@/src/ui';
import { storage } from '@/src/utils/storage';

type Tab = 'home'|'tools'|'work'|'diary'|'assistant';
export default function Index() {
  const {user,signOut,busy} = useAuth();
  const insets = useSafeAreaInsets();
  const [lang,setLang] = useState<Lang>('en');const [tab,setTab] = useState<Tab>('home');const [modal,setModal] = useState('');const [refreshKey,setRefreshKey]=useState(0);const [accountError,setAccountError]=useState('');
  const location = useFarmLocation();
  useEffect(()=>{void storage.getItem<string>('krushi_language','en').then(value=>setLang(value==='mr'?'mr':'en'));},[]);
  const toggleLanguage=()=>{const next=lang==='en'?'mr':'en';setLang(next);void storage.setItem('krushi_language',next);};
  const action=(value:string)=>{if(['tools','work','diary','assistant'].includes(value))setTab(value as Tab);else setModal(value);};
  const tabs: {id:Tab;icon:IconName;en:string;mr:string}[]=[{id:'home',icon:'home-outline',en:'Home',mr:'होम'},{id:'tools',icon:'construct-outline',en:'Rentals',mr:'भाडे'},{id:'work',icon:'people-outline',en:'Work',mr:'काम'},{id:'diary',icon:'journal-outline',en:'Diary',mr:'डायरी'},{id:'assistant',icon:'chatbubble-ellipses-outline',en:'Ask AI',mr:'विचारा'}];
  const logout=async()=>{try{await signOut();}catch(e){setAccountError(messageOf(e));}};
  return <View testID="app-root" style={[s.screen,{paddingTop:insets.top}]}>
    <View style={styles.header}><Pressable testID="location-picker-trigger" accessibilityRole="button" onPress={()=>setModal('location')} style={[s.row,s.flex,styles.location]}><View style={styles.brandIcon}><Icon name="leaf" size={19} color={colors.brandSecondary}/></View><View style={s.flex}><Text style={styles.brand}>KRUSHI RAKSHA</Text><View style={[s.row,{gap:4}]}><Icon name="location-outline" size={11} color={colors.muted}/><Text testID="header-location" style={styles.locationLabel} numberOfLines={1}>{location.location?.name||tr(lang,location.loading?'Finding location…':'Choose location',location.loading?'ठिकाण शोधत आहे…':'ठिकाण निवडा')}</Text><Icon name="chevron-down" size={12} color={colors.muted}/></View></View></Pressable><Pressable testID="language-toggle-button" accessibilityRole="button" onPress={toggleLanguage} style={styles.lang}><Text style={styles.langText}>{lang==='en'?'मराठी':'ENG'}</Text></Pressable><Pressable testID="user-profile-button" accessibilityRole="button" accessibilityLabel="Your account" onPress={()=>setModal('account')} style={styles.avatar}><Text style={styles.avatarText}>{user?.name.slice(0,1).toUpperCase()}</Text></Pressable></View>
    <Enter key={tab}>{tab==='home'?<Home lang={lang} location={location.location} locating={location.loading} locationError={location.error} onLocation={()=>setModal('location')} onAction={action} refreshKey={refreshKey}/>:tab==='tools'||tab==='work'?<Market key={tab} board={tab} lang={lang} location={location.location} onLocation={()=>setModal('location')}/>:tab==='diary'?<Diary lang={lang}/>:<Assistant lang={lang}/>}</Enter>
    <View testID="bottom-nav" style={[styles.nav,{paddingBottom:Math.max(insets.bottom,10)}]}>{tabs.map(item=><Pressable key={item.id} testID={`nav-tab-${item.id}`} accessibilityRole="tab" accessibilityState={{selected:tab===item.id}} onPress={()=>setTab(item.id)} style={({pressed})=>[styles.navItem,pressed&&s.pressed]}><View style={[styles.navIcon,tab===item.id&&styles.navIconSelected]}><Icon name={item.icon} size={21} color={tab===item.id?colors.brandSecondary:colors.muted}/></View><Text style={[styles.navLabel,tab===item.id&&styles.navLabelSelected]}>{tr(lang,item.en,item.mr)}</Text></Pressable>)}</View>
    {modal==='location'&&<LocationPicker lang={lang} location={location.location} onSelect={location.select} onGps={location.useGps} onClose={()=>setModal('')}/>}
    {modal==='diagnosis'&&<DiagnosisSheet lang={lang} onClose={()=>setModal('')}/>}{modal==='land'&&<LandSheet lang={lang} onClose={()=>setModal('')}/>}{modal==='crop'&&<CropSheet lang={lang} onClose={()=>setModal('')} onSaved={()=>{setModal('');setRefreshKey(v=>v+1);showToast(tr(lang,'Crop added','पीक जोडले'));}}/>}
    {modal==='account'&&<Sheet id="account-modal" title={tr(lang,'Your account','तुमचे खाते')} onClose={()=>setModal('')}><Badge id="account-google-badge" label={tr(lang,'SIGNED IN WITH GOOGLE','GOOGLE द्वारे साइन इन')}/><Text testID="account-name" style={s.h2}>{user?.name}</Text><Text testID="account-email" style={s.body}>{user?.email}</Text><Text testID="account-privacy-note" style={s.body}>{tr(lang,'Your crops, diary, diagnosis results and AI conversations are private. Listings you publish are visible to the local community; only you manage them.','तुमची पिके, डायरी, निदान आणि AI संभाषणे खाजगी आहेत. प्रकाशित जाहिराती समुदायाला दिसतात; केवळ तुम्ही त्या व्यवस्थापित करता.')}</Text>{location.location&&<Text testID="account-location-accuracy" style={s.caption}>{location.location.source==='gps'?`${tr(lang,'GPS accuracy','GPS अचूकता')}: ${location.location.accuracy!=null?`±${Math.round(location.location.accuracy)} m`:tr(lang,'not reported','माहिती नाही')}`:tr(lang,'Manual village/city location','गाव/शहर स्वतः निवडलेले')}</Text>}<Button id="account-location-button" label={tr(lang,'Change location','ठिकाण बदला')} secondary icon="locate-outline" onPress={()=>setModal('location')}/><ErrorNote id="account-error" text={accountError}/><Button id="google-signout-button" label={tr(lang,'Sign out','साइन आउट')} secondary icon="log-out-outline" busy={busy} onPress={()=>void logout()}/></Sheet>}
    <ToastHost/>
  </View>;
}
const styles=StyleSheet.create({header:{paddingHorizontal:20,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.surface},brandIcon:{width:36,height:40,alignItems:'center',justifyContent:'center'},brand:{fontSize:11,fontWeight:'800',letterSpacing:1.1,color:colors.onSurface,marginBottom:5},location:{minHeight:44,gap:7},locationLabel:{fontSize:11,color:colors.muted,flexShrink:1},lang:{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center'},langText:{fontSize:12,fontWeight:'600',color:colors.onSurfaceSecondary},avatar:{width:44,height:44,borderRadius:15,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.brandTertiary,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:17,fontWeight:'600',color:colors.onBrandTertiary},nav:{flexDirection:'row',paddingTop:8,borderTopWidth:1,borderTopColor:colors.border,backgroundColor:colors.surfaceSecondary},navItem:{flex:1,minHeight:56,alignItems:'center',justifyContent:'center',gap:4},navIcon:{width:44,height:30,borderRadius:10,alignItems:'center',justifyContent:'center'},navIconSelected:{backgroundColor:colors.brandTertiary},navLabel:{fontSize:10,color:colors.muted,fontWeight:'500'},navLabelSelected:{color:colors.brandSecondary}});