import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, Text, View } from 'react-native';
import { createDiary, DiaryEntry, getDiary, request } from '../api';
import { colors } from '../theme';
import { showToast } from '../toast';
import { Button, Chips, dateLabel, Empty, ErrorNote, Field, IconButton, Lang, messageOf, money, PageTitle, s, Sheet, tr } from '../ui';

const types = (lang: Lang) => [['irrigation','Irrigation','पाणी'],['fertilizer','Fertilizer','खत'],['spray','Spray','फवारणी'],['expense','Expense','खर्च'],['harvest','Harvest','कापणी']].map(([value,en,mr]) => ({value,label:tr(lang,en,mr)}));
export default function Diary({lang}: {lang: Lang}) {
  const [entries,setEntries] = useState<DiaryEntry[]>([]); const [loading,setLoading] = useState(true);
  const [add,setAdd] = useState(false); const [remove,setRemove] = useState<DiaryEntry | null>(null); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const load = useCallback(async () => {setLoading(true); try{setEntries(await getDiary());setError('');}catch(e){setError(messageOf(e));}finally{setLoading(false);}},[]);
  useEffect(() => {void load();},[load]);
  const deleteEntry = async () => {if (!remove) return;setBusy(true);try{await request(`/diary/${remove.id}`,{method:'DELETE'});setRemove(null);await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
  return <View style={s.screen}><ScrollView testID="diary-screen" contentContainerStyle={s.content}><PageTitle id="diary" eyebrow={tr(lang,'YOUR PRIVATE FIELD NOTES','तुमच्या खाजगी शेत नोंदी')} title={tr(lang,'Crop diary','पीक डायरी')} subtitle={tr(lang,'Small notes. Better decisions.','छोट्या नोंदी. चांगले निर्णय.')} action={<IconButton id="diary-add-button" label="Add diary entry" icon="add" onPress={() => setAdd(true)}/>}/>
    <View style={[s.card,s.row]}><View style={s.flex}><Text style={s.caption}>{tr(lang,'Activities','कामाच्या नोंदी')}</Text><Text style={s.h1} testID="diary-entry-count">{entries.length}</Text></View><View style={s.flex}><Text style={s.caption}>{tr(lang,'Expenses logged','नोंदवलेला खर्च')}</Text><Text style={s.h2} testID="diary-expense-total">{money(entries.reduce((sum,e)=>sum+(e.amount||0),0))}</Text></View></View>
    <ErrorNote id="diary-error" text={error}/>{!!error && <Button id="diary-retry-button" label={tr(lang,'Try again','पुन्हा प्रयत्न करा')} secondary onPress={() => void load()}/>}
    {loading ? <ActivityIndicator color={colors.brandSecondary}/> : entries.length ? entries.map(entry => <View key={entry.id} testID={`diary-entry-${entry.id}`} style={s.card}><View style={[s.row,s.between]}><Text style={s.eyebrow}>{dateLabel(entry.created_at,lang)}</Text><IconButton id={`diary-delete-${entry.id}`} label="Delete entry" icon="trash-outline" onPress={() => setRemove(entry)}/></View><Text style={s.h3}>{lang === 'mr' && entry.title_mr ? entry.title_mr : entry.title}</Text><Text style={s.caption}>{entry.crop_name} · {types(lang).find(t => t.value === entry.activity_type)?.label} {entry.amount ? `· ${money(entry.amount)}` : ''}</Text>{!!entry.notes && <Text style={s.body}>{entry.notes}</Text>}</View>) : !error && <Empty id="diary-empty" icon="journal-outline" title={tr(lang,'Every season tells a story','प्रत्येक हंगामाची एक गोष्ट')} detail={tr(lang,'Keep track of irrigation, expenses and everything you do for your crops. Only you can see these notes.','पाणी, खर्च आणि पिकांसाठी केलेल्या कामांची नोंद ठेवा. या नोंदी केवळ तुम्हालाच दिसतात.')}><Button id="diary-empty-add-button" label={tr(lang,'Log your first activity','पहिल्या कामाची नोंद करा')} onPress={() => setAdd(true)}/></Empty>}
  </ScrollView>{add && <DiaryForm lang={lang} onClose={() => setAdd(false)} onSaved={() => {setAdd(false);void load();showToast(tr(lang,'Diary entry saved','डायरी नोंद जतन झाली'));}}/>}{remove && <Sheet id="delete-diary-modal" title={tr(lang,'Delete this entry?','ही नोंद हटवायची?')} onClose={() => setRemove(null)}><Text style={s.body}>{remove.title}</Text><Text style={s.caption}>{tr(lang,'This cannot be undone.','ही कृती पूर्ववत करता येणार नाही.')}</Text><ErrorNote id="delete-diary-error" text={error}/><Button id="confirm-delete-diary" label={tr(lang,'Delete entry','नोंद हटवा')} busy={busy} onPress={() => void deleteEntry()}/></Sheet>}</View>;
}
function DiaryForm({lang,onClose,onSaved}: {lang: Lang; onClose: () => void; onSaved: () => void}) {
  const [type,setType] = useState('irrigation'); const [crop,setCrop] = useState(''); const [title,setTitle] = useState(''); const [notes,setNotes] = useState(''); const [amount,setAmount] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const save = async () => {
    if (!title.trim() || !crop.trim()) {setError(tr(lang,'Add a crop and activity title.','पीक आणि कामाचे शीर्षक भरा.'));return;}
    if (amount && (!Number.isFinite(Number(amount)) || Number(amount)<0)) {setError(tr(lang,'Enter a valid, non-negative amount.','शून्य किंवा त्यापेक्षा जास्त रक्कम भरा.'));return;}
    setBusy(true);setError('');try{await createDiary({crop_id:'manual',crop_name:crop.trim(),activity_type:type as DiaryEntry['activity_type'],title:title.trim(),title_mr:lang==='mr'?title.trim():'',notes:notes.trim(),amount:amount?Number(amount):undefined});onSaved();}catch(e){setError(messageOf(e));}finally{setBusy(false);}
  };
  return <Sheet id="diary-modal" title={tr(lang,'Log field activity','शेतातील काम नोंदवा')} onClose={onClose}><Chips id="diary-type" value={type} onChange={setType} items={types(lang)}/><Field id="diary-crop-input" label={tr(lang,'Crop','पीक')} value={crop} onChangeText={setCrop} placeholder={tr(lang,'e.g. Soybean','उदा. सोयाबीन')} maxLength={80}/><Field id="diary-title-input" label={tr(lang,'What happened?','काय झाले?')} value={title} onChangeText={setTitle} placeholder={tr(lang,'e.g. Irrigated the north field','उदा. उत्तर शेताला पाणी दिले')} maxLength={150}/><Field id="diary-notes-input" label={tr(lang,'Notes (optional)','तपशील (ऐच्छिक)')} value={notes} onChangeText={setNotes} multiline maxLength={3000}/><Field id="diary-amount-input" label={tr(lang,'Amount spent (₹, optional)','खर्च (₹, ऐच्छिक)')} value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><ErrorNote id="diary-form-error" text={error}/><Button id="diary-save-button" label={tr(lang,'Save activity','काम जतन करा')} icon="checkmark" busy={busy} onPress={() => void save()}/></Sheet>;
}