import { Image } from 'expo-image';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Dashboard, getDashboard } from '../api';
import { useAuth } from '../auth';
import { FarmLocation } from '../local-api';
import { colors } from '../theme';
import { Badge, Button, Empty, ErrorNote, Icon, IconName, Lang, messageOf, s, tr } from '../ui';
import { FARM_IMAGE } from './Welcome';

export default function Home({lang, location, locating, locationError, onLocation, onAction, refreshKey}: {lang: Lang; location: FarmLocation | null; locating: boolean; locationError: string; onLocation: () => void; onAction: (action: string) => void; refreshKey: number}) {
  const {user} = useAuth();
  const [data,setData] = useState<Dashboard | null>(null); const [loading,setLoading] = useState(false); const [error,setError] = useState('');
  const load = useCallback(async () => {
    if (!location) return;
    setLoading(true); setError('');
    try {setData(await getDashboard(location.latitude,location.longitude));} catch(e){setError(messageOf(e));} finally{setLoading(false);}
  },[location]);
  useEffect(() => {setData(null); void load();},[load,refreshKey]);
  const weather = data?.weather;
  const actions: {id: string; icon: IconName; en: string; mr: string; caption: string; captionMr: string}[] = [
    {id:'diagnosis',icon:'scan-outline',en:'Crop diagnosis',mr:'पीक निदान',caption:'A second look, with AI',captionMr:'AI सह पिकाची तपासणी'},
    {id:'land',icon:'document-text-outline',en:'7/12 records',mr:'७/१२ उतारा',caption:'Official portal guide',captionMr:'अधिकृत पोर्टल मार्गदर्शक'},
  ];
  const conditions = !weather?.available ? tr(lang,'Weather unavailable','हवामान उपलब्ध नाही') : (weather.rain_probability ?? 0) >= 60 ? tr(lang,'Rain may be on the way','पाऊस येण्याची शक्यता') : tr(lang,'Your field, at a glance','तुमच्या शेताची थोडक्यात माहिती');
  return <ScrollView testID="home-screen" contentContainerStyle={s.content} showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor={colors.brandSecondary}/>}>
    <View style={s.titleWrap}><Text testID="home-date" style={s.eyebrow}>{new Date().toLocaleDateString(lang === 'mr' ? 'mr-IN' : 'en-IN',{weekday:'long',day:'numeric',month:'long'}).toUpperCase()}</Text><Text testID="home-greeting" style={s.h1}>{tr(lang,'Namaskar,','नमस्कार,')} {user?.name.split(' ')[0]}.</Text><Text style={s.subtitle}>{tr(lang,'A good day starts with a clear view.','दिवसाची सुरुवात स्पष्ट माहितीसह.')}</Text></View>
    {!!error && <><ErrorNote id="dashboard-error" text={error}/><Button id="dashboard-retry-button" label={tr(lang,'Refresh weather','हवामान पुन्हा तपासा')} secondary onPress={() => void load()}/></>}
    {location ? <View style={styles.weather} testID="weather-card"><Image source={FARM_IMAGE} style={styles.weatherPhoto} contentFit="cover"/><View style={styles.weatherShade}/><View style={styles.weatherBody}><View style={[s.row,s.between]}><Text style={styles.lightLabel}>{tr(lang,'FIELD WEATHER','शेतातील हवामान')}</Text><Badge id="weather-live-status" label={weather?.available ? tr(lang,'LIVE','थेट') : loading ? tr(lang,'UPDATING','अपडेट होत आहे') : tr(lang,'UNAVAILABLE','उपलब्ध नाही')}/></View><View style={[s.row,s.between]}><Text testID="weather-temperature" style={styles.temperature}>{weather?.available ? `${weather.temperature_c}°` : '—'}<Text style={styles.unit}> C</Text></Text><Icon name={(weather?.rain_probability ?? 0) >= 60 ? 'rainy-outline' : 'partly-sunny-outline'} size={52} color={colors.brandSecondary}/></View><Text testID="weather-condition" style={styles.condition}>{conditions}</Text><Text testID="weather-location" style={styles.lightLabel} numberOfLines={1}>{location.name}</Text></View><View style={styles.metrics}>{[['rainy-outline',tr(lang,'Rain','पाऊस'),weather?.rain_probability,'%'],['water-outline',tr(lang,'Humidity','आर्द्रता'),weather?.humidity,'%'],['speedometer-outline',tr(lang,'Wind','वारा'),weather?.wind_kmh,' km/h']].map(([icon,label,value,unit],i) => <View key={i} style={styles.metric}><Icon name={icon as IconName} color={colors.onBrandTertiary} size={17}/><Text testID={`weather-metric-${i}`} style={styles.metricValue}>{weather?.available ? `${value}${unit}` : '—'}</Text><Text style={s.caption}>{label}</Text></View>)}</View></View> : <Empty id="home-location-empty" icon="locate-outline" title={tr(lang,locating ? 'Finding your field…' : 'Make it local',locating ? 'तुमचे शेत शोधत आहे…' : 'तुमचा परिसर निवडा')} detail={tr(lang,'Choose your location for weather, equipment and work near you.','हवामान, अवजारे आणि कामासाठी ठिकाण निवडा.')}>{locating ? <ActivityIndicator color={colors.brandSecondary}/> : <Button id="home-choose-location" label={tr(lang,'Choose location','ठिकाण निवडा')} onPress={onLocation}/>}</Empty>}
    {!location && !locating && !!locationError && <Text testID="home-location-error" style={s.caption}>{locationError}</Text>}
    {data?.risks.slice(0,1).map(risk => <View testID={`risk-card-${risk.id}`} key={risk.id} style={styles.alert}><Icon name="shield-checkmark-outline" color={colors.brandSecondary}/><View style={s.flex}><Text style={s.h3}>{lang === 'mr' ? risk.title_mr : risk.title}</Text><Text style={s.subtitle}>{lang === 'mr' ? risk.description_mr : risk.description}</Text></View></View>)}
    <View style={styles.section}><Text style={s.h2}>{tr(lang,'Your farm toolkit','तुमच्या शेतीसाठी')}</Text><Text style={s.caption}>{tr(lang,'Care for every acre','प्रत्येक एकराची काळजी')}</Text></View>
    <View style={styles.actionRow}>{actions.map(action => <Pressable testID={`action-${action.id}-button`} key={action.id} onPress={() => onAction(action.id)} style={({pressed}) => [styles.action, pressed && s.pressed]}><View style={styles.actionIcon}><Icon name={action.icon} color={colors.brandSecondary}/></View><Text style={s.h3}>{tr(lang,action.en,action.mr)}</Text><Text style={s.caption}>{tr(lang,action.caption,action.captionMr)}</Text><Icon name="arrow-forward" size={17} color={colors.muted}/></Pressable>)}</View>
    <Pressable testID="home-community-button" onPress={() => onAction('tools')} style={({pressed}) => [s.card,s.row,pressed && s.pressed]}><Icon name="people-outline" size={28} color={colors.brandSecondary}/><View style={s.flex}><Text style={s.h3}>{tr(lang,'Better, together.','एकत्रित प्रगती.')}</Text><Text style={s.subtitle}>{tr(lang,'Rent tools and find farm help nearby.','जवळपास अवजारे आणि शेतीसाठी मदत शोधा.')}</Text></View><Icon name="arrow-forward" size={20}/></Pressable>
    <View style={[s.row,s.between]}><Text style={s.h2}>{tr(lang,'My crops','माझी पिके')}</Text><Pressable testID="add-crop-button" accessibilityRole="button" onPress={() => onAction('crop')} style={styles.add}><Icon name="add" color={colors.brandSecondary} size={18}/><Text style={styles.addText}>{tr(lang,'Add crop','पीक जोडा')}</Text></Pressable></View>
    {data?.crops.length ? data.crops.map(crop => <View key={crop.id} testID={`crop-card-${crop.id}`} style={s.card}><View style={s.row}><View style={styles.actionIcon}><Icon name="leaf-outline" color={colors.success}/></View><View style={s.flex}><Text style={s.h3}>{crop.name}</Text><Text style={s.caption}>{crop.variety ? `${crop.variety} · ` : ''}{crop.area_acres} {tr(lang,'acres','एकर')}</Text></View></View><Text style={s.body}>{tr(lang,crop.next_action,crop.next_action_mr)}</Text><Text style={s.caption}>{tr(lang,'Health measurements are not available. Use crop diagnosis for guidance.','आरोग्य मोजमाप उपलब्ध नाही. मार्गदर्शनासाठी पीक निदान वापरा.')}</Text></View>) : <View testID="crops-empty" style={s.card}><Text style={s.body}>{tr(lang,'Your crops belong here. Add a crop to start your personal field record.','तुमची पिके येथे नोंदवा. वैयक्तिक शेत नोंदीसाठी पीक जोडा.')}</Text></View>}
    <Text testID="home-advisory-disclaimer" style={[s.caption,s.center]}>{tr(lang,'Weather by Open-Meteo. Farm guidance supports, not replaces, advice from a local agronomist.','हवामान: Open-Meteo. मार्गदर्शन स्थानिक कृषी तज्ज्ञांच्या सल्ल्याची जागा घेत नाही.')}</Text>
  </ScrollView>;
}
const styles = StyleSheet.create({weather: {backgroundColor: colors.brand, borderWidth: 1, borderColor: colors.border, borderRadius: 24, overflow: 'hidden'}, weatherPhoto: {position:'absolute',top:0,right:0,width:'100%',height:225,opacity:0.24}, weatherShade: {position:'absolute',top:0,right:0,left:0,height:225,backgroundColor:colors.photoShade}, weatherBody: {padding:22,gap:8}, lightLabel: {color: colors.onBrandTertiary,fontSize:11,fontWeight:'500',letterSpacing:0.7}, temperature: {fontSize:64,lineHeight:78,fontWeight:'500',letterSpacing:-3,color:colors.onSurface}, unit: {fontSize:20,letterSpacing:0}, condition: {fontSize:15,color:colors.onSurface,fontWeight:'500'}, metrics: {flexDirection:'row',backgroundColor:colors.surfaceSecondary,paddingVertical:17,borderTopWidth:1,borderColor:colors.border}, metric: {flex:1,alignItems:'center',gap:5}, metricValue: {fontSize:16,fontWeight:'600',color:colors.onSurface}, alert: {flexDirection:'row',gap:12,padding:17,borderRadius:16,backgroundColor:colors.surfaceTertiary,borderLeftWidth:3,borderLeftColor:colors.brandSecondary}, section: {gap:3,marginTop:6}, actionRow: {flexDirection:'row',gap:12}, action: {flex:1,backgroundColor:colors.surfaceSecondary,borderWidth:1,borderColor:colors.divider,borderRadius:18,padding:17,gap:12}, actionIcon: {width:42,height:42,borderRadius:12,backgroundColor:colors.surfaceTertiary,alignItems:'center',justifyContent:'center'}, add: {minHeight:44,flexDirection:'row',alignItems:'center',gap:4}, addText: {fontSize:13,fontWeight:'600',color:colors.brandSecondary}});